[package]
name = "entity"
version = "0.1.0"
edition.workspace = true
readme.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
sea-orm.workspace = true
serde.workspace = true
chrono.workspace = true
